# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 04:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linkstart', '0004_auto_20171123_2359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='index',
            old_name='content_1',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='index',
            name='content_2',
        ),
        migrations.RemoveField(
            model_name='index',
            name='content_3',
        ),
        migrations.RemoveField(
            model_name='index',
            name='content_4',
        ),
        migrations.RemoveField(
            model_name='index',
            name='content_5',
        ),
        migrations.RemoveField(
            model_name='index',
            name='content_6',
        ),
    ]
